### ISSUE TITLE
日志无法关闭

### ISSUE THREAD

**Issue by Gooe** [baiy/think-async#2]
Async::setLog(new \Psr\Log\NullLogger());
使用这个方法也无法关闭

**Comment by baiy** [comment]
> Async::setLog(new \Psr\Log\NullLogger());
> 使用这个方法也无法关闭

你这个代码填在在什么位置   把这段代码添加在 系统服务系统方法中试试 `boot()`

**Comment by Gooe** [comment]
> > Async::setLog(new \Psr\Log\NullLogger());
> > 使用这个方法也无法关闭
> 
> 你这个代码填在什么位置把这个代码添加在系统服务系统中的方法中 `boot()`

![image](https://user-images.githubusercontent.com/5295090/129665051-02616e60-6edc-46e6-bbc9-13bb55d30ef8.png)

放在其它位置都不能，只能放这里有效，但是这样修改了你的扩展

**Comment by baiy** [comment]
放在
<https://github.com/top-think/think/blob/b706e89936ac2aa7316fb94bb2e66c32028d62ba/app/AppService.php#L18-L21>

**Comment by Gooe** [comment]
> 放在
> https://github.com/top-think/think/blob/b706e89936ac2aa7316fb94bb2e66c32028d62ba/app/AppService.php#L18-L21

嗯，可以了
